spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      dll-auto: update
  h2:
    console.enabled: true
security:
  secret:
    password:
      key: 1234567890123456 #Carga en secret
    key: afafasfafafasfasfasfafacasdasfasxASFACASDFACASDFASFASFDAFASFASDAADSCSDFADCVSGCFVADXCcadwavfsfarvf #Carga en secret
format:
  email:
    regex: ^[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$
  password:
    regex: ^(?=(?:[^A-Z]*[A-Z][^A-Z]*)$)(?=(?:[^0-9]*[0-9][^0-9]*[0-9][^0-9]*)$)[a-zA-Z0-9]{8,12}$
    error: Password must contain exactly one uppercase letter, exactly two digits (0–9), only lowercase letters otherwise, no special characters or spaces, and must be between 8 and 12 characters long.